use new image
NYCPlanning/data-engineering pull request #37
Opened 2023-07-05 16:12 UTC by fvankrieken

Should have gotten this in with the last PR but missed it - get pluto building on our image.

2023-07-06 13:55 UTC, fvankrieken commented
Added a new "actual" base image, without geosupport, as well as the geosupport image

New base image has size of 650 MB, going to see if I can get it down

2023-07-06 13:57 UTC, fvankrieken commented on bash/utils.sh
> +    local branchname=$(cat .git/HEAD | cut -d '/' -f3)
Removed dependency on git for checking branch! This would have solved the devdb issue as well.

2023-07-06 14:42 UTC, fvankrieken commented
Building with more lightweight image! Though now having the error seen in devdb so this PR is blocked by #32

2023-07-06 15:13 UTC, fvankrieken commented
Running one last build, sorry for early review tag, y'all can wait till this afternoon

https://github.com/NYCPlanning/data-engineering/actions/runs/5477153075

2023-07-06 15:14 UTC, fvankrieken commented on .github/workflows/developments_build.yml
> +      image: nycplanning/build-geosupport:latest
This image is identical, just more specific name now

2023-07-06 15:24 UTC, fvankrieken commented
Actuallly @damonmcc some food for thought - this uses ghcr.io/osgeo/gdal:ubuntu-small-3.6.4 as base image for the new container. The main point of this is to have gdal setup... but really I don't think we need anything for what we're doing other than `gdal-bin`. 

The bigger build image uses our latest geosupport image, which uses python:3.9-slim as it's base image. For the sake of consistency, I should probably start with that and add what we need from there, right? Also at some point worth upgrading that.

Really actually, maybe the docker-geosupport repo should be moved into this docker folder, so all of these can be managed together (and bound to the same base image, versioned in similar ways, etc)

2023-07-07 16:04 UTC, fvankrieken commented
@alexrichey note that docker images are changing (for FacDB assuming you're using in build), though I haven't deleted the original "base" one yet

2023-07-07 19:38 UTC, damonmcc requested changes

2023-07-07 19:38 UTC, damonmcc commented on db-pluto/pluto_build/bash/config.sh
> +
does this also need `set_env ../../.env`? wondering because it was deleted from all the `0X_step.sh` files

edit: you mentioned that you added that line in the `pluto_build/bash/config.sh`, but that's this file and I'm not seeing it

2023-07-07 19:59 UTC, fvankrieken commented on db-pluto/pluto_build/bash/config.sh
> +
You are correct

2023-07-07 20:08 UTC, fvankrieken commented on db-pluto/pluto_build/bash/config.sh
> +
Fixed

2023-07-07 20:43 UTC, damonmcc approved these changes

2023-07-07 20:44 UTC, merged